### PR TITLE
Initial Auk Feathers Chat API

### LINKED ISSUE #10: Prevent duplicate signups

### LINKED ISSUE #43: readme is dated
Readme is still showing yo generator instead of the new feathers-cli generator

### LINKED ISSUE #44: need to update to new common
Calling populate(target, options) is now DEPRECATED and will be removed in the future. Refer to docs.feathersjs.com for more information. (legacyPopulate)

### PR DESCRIPTION
**Pull request by daffl**
This is the new feathers-chat API for Auk. The setup is much more straightforward with only two easy to follow hooks and use of the populate common hook.

Closes #10, closes #43, closes #44

### CODE REVIEW

**Comment by marshallswain** [comment]
Looks really good.  I love the new structure.

**Comment by ekryski** [comment]
@daffl looks good. @marshallswain yeah this is the new generator structure which is pretty nice.

@daffl the only thing I might suggest we change here and in the generator is to make the filters files the same as the hooks.

- Have a global filters folder
- And have the filters.js file for each service look the same

I'm primarily suggesting that to give people an idea of how they should structure those. Pretty minor comments though and should not stop this from shipping.

:shipit:

**Comment by marshallswain** [comment]
@feathersjs/core-team what do you guys think about adding some super simple schema validation?  It's nice to have a place where you can see what the service expects to receive.

**Comment by daffl** [comment]
Isn't that done here already in the `process` hook? This initial version was the one that's going to be in the guide where I think schema validation might be a little too much.

**Comment by ekryski** [comment]
I agree with @daffl. Keep it simple. That should be a more advanced guide and might depend on the type of database you use.

**Pull request merged**
