### PR TITLE
Make it work in VueJS version 2

### PR DESCRIPTION
**Pull request by ais-one**

### CODE REVIEW

**Comment by daffl** [comment]
This looks good, thank you! Would you mind updating the guide at https://github.com/feathersjs/feathers-docs/blob/master/frameworks/vuejs.md accordingly if you have time?

**Comment by ais-one** [comment]
ok got update the guide (Can I do an append to the guide instead of a replace?)

**Comment by daffl** [comment]
We can make a copy of it so that Vue 2 gets its own section in the menu.

**Comment by psi-4ward** [comment]
Some Notes:

* `track-by` was replaced with `:key`
* Some guys suggested to use `<script type="text/x-template">` instead of `<template>` BUT they didn't have good arguments
* `v-for="(user, index) in users"` we can drop `index` cause we don't use it
* there is a much newer version of feather-client

**Pull request merged**
