### PR TITLE
Auk unique email

### PR DESCRIPTION
**Pull request by marshallswain**
This uses NeDB's [indexing feature](https://github.com/louischatriot/nedb#indexing) to make sure email addresses must be unique

### CODE REVIEW

**Comment by daffl** [comment]
Should be against the branch in #48 right?

**Comment by marshallswain** [comment]
Yeah.  Thanks.  I wondered why it was showing your commits.

**Comment by daffl** [comment]
This seems like something that should be added to the generated model?

**Comment by marshallswain** [comment]
I'm not sure.  We would have to ask for which fields they want to be unique, and we'd want the prompts to be consistent across database adapters.  I wouldn't want to generate indexes for Mongoose and Sequelize.

**Comment by daffl** [comment]
All use models flag the email field as unique (see the `-user` files in https://github.com/feathersjs/generator-feathers/tree/master/generators/service/templates/model). I don't think it hurts to add that index for NeDB to https://github.com/feathersjs/generator-feathers/blob/master/generators/service/templates/model/nedb-user.js

**Comment by marshallswain** [comment]
I see.  I'll add it there, too.

**Pull request closed without merging**
